using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum Phase {

    SETUP,
    SETUP_VIEW_RECEIVE_GOLD,
    SETUP_REVEALING_INFO,
    SETUP_VIEW_REVEALING_INFO,
    SETUP_ADDING_NEW_STUFF,
    SETUP_VIEW_ADDING_NEW_STUFF,
    GROUPING_PLAYER,
    VIEW_GROUPING_PLAYER,
    INPUT_GROUPING_PLAYER,
    SHOPPING_ACTIONS,
    ARRANGING_PETS,
    NEED_CARDS,
    EVALUATING_NEEDS,
    EXHIBITION,
    BUSINESS,
    USING_IMPS,
    AGING,
    STARTING_NEXT_ROUND
}
