using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum Phase {

    SETUP,
    SETUP_VIEW_RECEIVE_GOLD,
    SETUP_REVEALING_INFO,
    SETUP_VIEW_REVEALING_INFO,
    SETUP_ADDING_NEW_STUFF,
    SETUP_VIEW_ADDING_NEW_STUFF,

    SETUP_GROUPING_PLAYER,
    GROUPING_PLAYER,
    VIEW_GROUPING_PLAYER,
    INPUT_GROUPING_PLAYER,
    CHECK_GROUPING_PLAYERS,
    EVERYONE_GROUPED,

    SETUP_SHOPPING_ACTIONS,
    SHOPPING_ACTION,
    VIEW_SHOPPING_ACTION,
    INPUT_SHOPPING_ACTION,
    CHECK_SHOPPING_ACTIONS,
    EVERYONE_SHOPPED,

    SETUP_ARRANGING_PETS,
    ARRANGING_PETS,
    VIEW_ARRANGING_PETS,
    INPUT_ARRANGING_PETS,
    CHECK_ARRANGING_PETS,
    EVERYONE_ARRANGED,

    SETUP_NEED_CARDS,
    NEED_CARDS_DEALT,
    VIEW_NEED_CARDS_DEALT,
    INPUT_NEED_CARDS,
    EVALUATE_NEED_CARDS,
    VIEW_EVALUATE_NEED_CARDS,
    CHECK_NEED_CARDS,
    EVERYONE_NEEDED,

    EVALUATING_NEEDS,
    EXHIBITION,
    BUSINESS,
    USING_IMPS,
    AGING,
    STARTING_NEXT_ROUND
}
